enum CameraOrGallery {
  camera,
  gallery,
}

enum DockKeyPhotoMemo {
  title,
  memo,
  createdBy,
  photoFilename,
  photoURL,
  timestamp,
  sharedWith,
}

class PhotoMemo {
  String? docId; // generated by Firestore
  String createdBy; // email address of the user
  String title;
  String memo;
  String photoFilename;
  String photoURL; // given by Storage
  DateTime? timestamp;
  late List<dynamic> sharedWith;

  PhotoMemo({
    this.docId,
    required this.createdBy,
    required this.title,
    required this.memo,
    required this.photoFilename,
    required this.photoURL,
    this.timestamp,
    List<dynamic>? sharedWith,
  }) {
    this.sharedWith = sharedWith == null ? [] : [...sharedWith];
  }

  factory PhotoMemo.fromFirestoreDoc({
    required Map<String, dynamic> doc,
    required String docId,
  }) {
    return PhotoMemo(
      docId: docId,
      createdBy: doc[DockKeyPhotoMemo.createdBy.name] ?? '',
      title: doc[DockKeyPhotoMemo.title.name] ?? '',
      memo: doc[DockKeyPhotoMemo.memo.name] ?? '',
      photoFilename: doc[DockKeyPhotoMemo.photoFilename.name] ?? '',
      photoURL: doc[DockKeyPhotoMemo.photoURL.name] ?? '',
      sharedWith: doc[DockKeyPhotoMemo.sharedWith.name] ?? [],
      timestamp: doc[DockKeyPhotoMemo.timestamp.name] != null
          ? DateTime.fromMillisecondsSinceEpoch(
              doc[DockKeyPhotoMemo.timestamp.name].millisecondsSinceEpoch)
          : null,
    );
  }

  Map<String, dynamic> toFirestoreDoc() {
    return {
      DockKeyPhotoMemo.title.name: title,
      DockKeyPhotoMemo.createdBy.name: createdBy,
      DockKeyPhotoMemo.memo.name: memo,
      DockKeyPhotoMemo.photoFilename.name: photoFilename,
      DockKeyPhotoMemo.photoURL.name: photoURL,
      DockKeyPhotoMemo.timestamp.name: timestamp,
      DockKeyPhotoMemo.sharedWith.name: sharedWith,
    };
  }

  static String? validateTitle(String? value) {
    return value == null || value.trim().length < 2 ? 'Title too short' : null;
  }

  static String? validateMemo(String? value) {
    return value == null || value.trim().length < 7 ? 'Memo too short' : null;
  }

  static String? validateSharedWith(String? value) {
    if (value == null || value.trim().isEmpty) return null;

    List<String> emailList =
        value.trim().split(RegExp('(,|;| )+')).map((e) => e.trim()).toList();
    for (String e in emailList) {
      if (!(e.contains('@') && e.contains('.'))) {
        return 'Invalid email address: comma, semicolon, space separated list';
      }
    }
    return null;
  }
}
