// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9P93w7gGbFw01GE7Y6jO3NeUnarN3Pgo',
    appId: '1:941774624468:web:09dd5c9b6242038e4ccd41',
    messagingSenderId: '941774624468',
    projectId: 'mthorlikonda-cmsc5303-fl-3eb4a',
    authDomain: 'mthorlikonda-cmsc5303-fl-3eb4a.firebaseapp.com',
    storageBucket: 'mthorlikonda-cmsc5303-fl-3eb4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-mtEVEsGRQRdGNZjMMavPjMIYtDhHUI',
    appId: '1:941774624468:android:4663530887df2db74ccd41',
    messagingSenderId: '941774624468',
    projectId: 'mthorlikonda-cmsc5303-fl-3eb4a',
    storageBucket: 'mthorlikonda-cmsc5303-fl-3eb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4lKo_yQwnjoKyGq5XISL507zj6_T3XE',
    appId: '1:941774624468:ios:c481a1fefdd298d84ccd41',
    messagingSenderId: '941774624468',
    projectId: 'mthorlikonda-cmsc5303-fl-3eb4a',
    storageBucket: 'mthorlikonda-cmsc5303-fl-3eb4a.appspot.com',
    iosBundleId: 'edu.uco.mthorlikonda.cmsc5303.lesson6',
  );

}